
version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/monitoring/:/etc/prometheus/
    ports:
      - 9090:9090
    # Just to be able to scrap during development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - geocoder
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/monitoring/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - geocoder
  postgis:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: o2p
      POSTGRES_USER: o2p
      POSTGRES_PASSWORD: o2p
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - geocoder

  ingest:
    image: iboates/osm2pgsql:2.1.0
    profiles: [ingest]
    command: "-d o2p --style /data/map.style /data/mazowieckie-latest.osm.pbf"
    environment: 
      PGHOST: postgis 
      PGPORT: 5432 
      PGUSER: o2p 
      PGPASSWORD: o2p
    volumes: 
      - ./docker/data:/data
    networks:
      - geocoder
  indexer:
    build: ./indexer
    profiles: [index]
    environment:
      PGHOST: postgis 
      PGPORT: 5432 
      PGUSER: o2p 
      PGPASSWORD: o2p
    networks:
        - geocoder
  server:
    build: ./server
    ports:
      - "8081:8080"
    environment:
      PGHOST: postgis 
      PGPORT: 5432 
      PGUSER: o2p 
      PGPASSWORD: o2p
    init: true 
    networks:
        - geocoder    
  # Not really needed, but handy to explore the data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mproch@mproch.pl
      PGADMIN_DEFAULT_PASSWORD: o2p
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
        - geocoder

networks:
  geocoder:

volumes:
  postgis_data:
  pgadmin-data:

